### ISSUE TITLE
Coredump of 0.5.0 while scrobbling 

### ISSUE THREAD

**Issue by gbcox** [mariusor/mpris-scrobbler#90]
Attached file is coredumpctl info:
[coredump_181058.txt](https://github.com/mariusor/mpris-scrobbler/files/8671254/coredump_181058.txt)

Here is the backtrace:
(gdb) bt
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/strlen-vec.S:126
#1  0x00007fca749a0e2d in json_object_new_string (s=0x220 <error: Cannot access memory at address 0x220>) at /usr/src/debug/json-c-0.15-3.fc36.x86_64/json_object.c:1290
#2  0x00005633cf6694b1 in listenbrainz_api_build_request_scrobble (tracks=<optimized out>, track_count=<optimized out>, auth=0x5633d011bf80)
    at /usr/src/debug/mpris-scrobbler-0.5.0-1.fc36.x86_64/redhat-linux-build/../src/listenbrainz_api.h:175
#3  0x00005633cf66d5ea in listenbrainz_api_build_request_scrobble (auth=0x5633d011bf80, track_count=1, tracks=0x7ffcc42db940)
    at /usr/src/debug/mpris-scrobbler-0.5.0-1.fc36.x86_64/redhat-linux-build/../src/listenbrainz_api.h:154
#4  api_build_request_scrobble (handle=<optimized out>, auth=0x5633d011bf80, track_count=1, tracks=0x7ffcc42db940)
    at /usr/src/debug/mpris-scrobbler-0.5.0-1.fc36.x86_64/redhat-linux-build/../src/api.h:611
#5  api_request_do (build_request=0x5633cf66acf0 <api_build_request_scrobble>, track_count=1, tracks=0x7ffcc42db940, s=0x7ffcc42ddfd0)
    at /usr/src/debug/mpris-scrobbler-0.5.0-1.fc36.x86_64/redhat-linux-build/../src/scrobbler.h:196
#6  scrobbles_consume_queue (scrobbler=0x7ffcc42ddfd0) at /usr/src/debug/mpris-scrobbler-0.5.0-1.fc36.x86_64/redhat-linux-build/../src/scrobble.h:527
#7  0x00005633cf66d6d8 in queue (fd=<optimized out>, event=<optimized out>, data=<optimized out>)
    at /usr/src/debug/mpris-scrobbler-0.5.0-1.fc36.x86_64/redhat-linux-build/../src/sevents.h:203
#8  0x00007fca749d78c2 in event_process_active_single_queue (base=base@entry=0x5633d011b620, activeq=0x5633d011ba70, max_to_process=max_to_process@entry=2147483647, 
    endtime=endtime@entry=0x0) at /usr/src/debug/libevent-2.1.12-6.fc36.x86_64/event.c:1691
#9  0x00007fca749d928f in event_process_active (base=0x5633d011b620) at /usr/src/debug/libevent-2.1.12-6.fc36.x86_64/event.c:1783
#10 event_base_loop (base=0x5633d011b620, flags=0) at /usr/src/debug/libevent-2.1.12-6.fc36.x86_64/event.c:2006
#11 0x00005633cf66194a in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/mpris-scrobbler-0.5.0-1.fc36.x86_64/redhat-linux-build/../src/daemon.c:61
(gdb)

**Comment by gbcox** [comment]
Testing out with the curl patch.  Will advise.
